### ISSUE TITLE
Make a video to help people run their first baseline

### ISSUE THREAD

**Issue by jaderabbit** [masakhane-io/message-board#1]
Many participants need help getting started. At the moment, we do one-on-one mentorship to do this. This is not scalable, so we'd like to make a video to help people run their baselines. 

It would ideally be put onto a Masakhane youtube channel (which also needs to be created). 

Preferred to be contacted: Via Masakhane Slack

**Comment by juliakreutzer** [comment]
Done by @Kabongosalomon and @salomeyosei: https://www.youtube.com/watch?v=jOKy_AnyLic
